version: "3.8"
services:
  task-management-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - ./env/task-management.env
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgres
    volumes:
      - postgresdb-dev:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env

volumes:
  postgresdb-dev: